# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs: # là nơi khai báo cmd line được hỗ trợ bởi circle 
  # sử dụng cmd line của node 
  node: circleci/node@3.0.0
  slack: circleci/slack@4.4.0
jobs:
  check:
    docker:
      - image: circleci/node:12.13.0
    steps:
      - checkout
      - restore_cache:
          keys: 
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
          - node_modules
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "*This is a text notification*",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always
  deploy-aws:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "85:2d:8a:ec:46:24:c5:0a:82:cb:bd:a2:2d:fc:cb:f4"
      - run:
          name: pull code and start api_services
          command: ssh -oStrictHostKeyChecking=no ec2-user@3.143.216.10 -p 22 "cd /home/ec2-user/nodejs-aws-circleci; git pull origin main; npm install;pm2 restart all"
  deploy-deroku:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: deploy main to heroku
          command: |
            git push https://heroku:$MY_API_KEY@git.heroku.com/demo-node-circleci.git main
workflows:
  my-flow:
    jobs:
      - check:
          context: slack-secrets
      - deploy-deroku:
          requires: 
            - check
          filters:
            branches:
              only:
                - main

# restore_cache & save_cache : Khôi phục bộ đệm đã lưu trước đó dựa trên key . Ở đây mục đích muốn giữ lại node_modules để không phải tạo lại mỗi lần chạy npm install